---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: github
  label: github
- type: text
  name: web
  label: web
- type: textarea
  name: description
  label: description
- type: file
  name: preview_img
  label: preview_img
- name: tags
  type: tag_list
  default: []
  label: Technology Tags
  description: A list of the technologies used on this project
pages:
- content/projects/firebase-authentication-client.md
- content/projects/timecards.md
